name: naycain
favicon: null
layout_spectrum: 0.403390608727932
typography_spectrum: 0.9717420318629593
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5961958144325763
  lightness: 0.5983916448894888
  saturation: 0.11177343153394759
  rhythmicContrast: 0.38909837882965803
purpose: []
